# system setup
sudo: required

# setup language
language: go
go:
  - "1.11"

install:
  # download our task runner
  - go get github.com/AlecAivazis/run
  # install the ci dependencies
  - run install:ci

script:
  # install the dependencies
  - run install
  # generate and report the test coverage
  - run test:coverage

before_deploy:
  - go get github.com/tcnksm/ghr
  # build the binaries
  - run build

deploy:
  # only deploy on tagged releases
  on:
    tags: true
  # we need to push a github release with this tag
  provider: script
  skip_cleanup: true
  script: |-
    ghr -t ${GITHUB_TOKEN} \
      -u "AlecAivazis" \
      -r "graphql-gateway" \
      -c ${TRAVIS_PULL_REQUEST_SHA} \
      -delete ${TRAVIS_TAG} ./bin/
