# system setup
sudo: required

# setup language
language: go
go:
  - "1.11"

install:
  # download our task runner
  - go get github.com/AlecAivazis/run
  # install the ci dependencies
  - run install-ci

script:
  - go test -v -covermode=atomic -coverprofile=coverage.out ./...
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
