# system setup
sudo: required

# setup language
language: go
go:
  - "1.11"

install:
  # download our task runner
  - go get github.com/AlecAivazis/run
  # install the ci dependencies
  - run install-ci

script:
  # generate and report the test coverage
  - run test:coverage
