name: Run Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install go
        uses: actions/setup-go@master
        with:
          version: 1.12

      - name: Install dependencies
        run: go install github.com/alecaivazis/run
