name: Precheck

# run this workflow on commits and pull requests
on: [push, pull_request]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout source
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Install runner
        run: go get github.com/alecaivazis/run

      - name: Install Dependencies
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          run install:ci

      - name: Run Tests
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          run tests:coverage
