name: Precheck

# run this workflow on commits and pull requests
on: [push, pull_request]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        id: go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout source
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
          path: ${{ go.module-path }}

      - name: Install Dependencies
        run: |
          # add executables installed with go get to PATH
          # https://github.com/actions/setup-go/issues/14
          export PATH=${PATH}:`go env GOPATH`/bin
          go get github.com/alecaivazis/run
          run install:ci
        working-directory: ${{ go.module-path }}

      - name: Run Tests
        run: run tests:coverage
        working-directory: ${{ go.module-path }}
